FROM tensorflow/tensorflow:1.7.1-gpu
WORKDIR /workdir
COPY facenet /workdir/
COPY VGGFace2-PretrainedModel /VGGFace2-PretrainedModel
RUN python -m pip install -r requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:/workdir/contributed"
ENV PYTHONPATH "${PYTHONPATH}:/workdir/src"
RUN cd /VGGFace2-PretrainedModel&& cat x* > model.zip && unzip model.zip
ENTRYPOINT python /workdir/contributed/export_embeddings.py --is_aligned False --outputfolder /output /VGGFace2-PretrainedModel/20180402-114759 /inputdata